module Spor.Token.Size.Spacing exposing (Spacing, toCss, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i0.5, i1.5)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Spacing, toCss, i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i0.5, i1.5
-}

import Css

{-| An opaque type representing a Spacing value.
-}
type Spacing =
    Spacing Css.Px

{-| Convert Spacing into Css.Px.
-}
toCss : Spacing -> Css.Px
toCss (Spacing value) =
    value

{-| 
-}
i0 : Spacing
i0 =
    Spacing <| Css.px 0


{-| This is the base spacing value
-}
i1 : Spacing
i1 =
    Spacing <| Css.px 6


{-| 
-}
i2 : Spacing
i2 =
    Spacing <| Css.px 12


{-| 
-}
i3 : Spacing
i3 =
    Spacing <| Css.px 18


{-| 
-}
i4 : Spacing
i4 =
    Spacing <| Css.px 24


{-| 
-}
i5 : Spacing
i5 =
    Spacing <| Css.px 30


{-| 
-}
i6 : Spacing
i6 =
    Spacing <| Css.px 36


{-| 
-}
i7 : Spacing
i7 =
    Spacing <| Css.px 42


{-| 
-}
i8 : Spacing
i8 =
    Spacing <| Css.px 54


{-| 
-}
i9 : Spacing
i9 =
    Spacing <| Css.px 72


{-| 
-}
i10 : Spacing
i10 =
    Spacing <| Css.px 90


{-| 
-}
i11 : Spacing
i11 =
    Spacing <| Css.px 120


{-| 
-}
i12 : Spacing
i12 =
    Spacing <| Css.px 180


{-| 
-}
i0.5 : Spacing
i0.5 =
    Spacing <| Css.px 3


{-| 
-}
i1.5 : Spacing
i1.5 =
    Spacing <| Css.px 9

